USE MYSQL_TRAINING;

DROP TABLE SUBJECT;
DROP TABLE BOOK;

CREATE TABLE SUBJECT (
	SUBJECTID int8 NOT NULL AUTO_INCREMENT,
    SUBTITLE VARCHAR(50) NOT NULL,
    DURATIONINHOURS INT(100) NOT NULL,
    BOOKID int8 NOT NULL,
    PRIMARY KEY (SUBJECTID)
);

CREATE TABLE BOOK (
	BOOKID int8 NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(50) NOT NULL,
    PRICE DOUBLE NOT NULL,
    VOLUME INT(3),
    PUBLISHDATE DATE NOT NULL,
    PRIMARY KEY (BOOKID)
);

ALTER TABLE SUBJECT
	ADD FOREIGN KEY (BOOKID) REFERENCES BOOK(BOOKID);